import { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import './ConsultationSummary.css';

const ConsultationSummary = () => {
    const { appointmentId } = useParams();
    const navigate = useNavigate();
    const { user } = useAuth();

    // Rating state
    const [rating, setRating] = useState(0);
    const [hoveredRating, setHoveredRating] = useState(0);
    const [feedback, setFeedback] = useState('');
    const [isSubmitted, setIsSubmitted] = useState(false);
    const [isDownloading, setIsDownloading] = useState(false);

    // Mock consultation data (in real app, fetch from API)
    const consultationData = {
        doctorName: 'Dr. Sarah Johnson',
        specialty: 'Cardiologist',
        date: new Date().toLocaleDateString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        }),
        duration: '15 minutes',
        diagnosis: 'Mild anxiety-related chest discomfort',
        recommendations: [
            'Regular exercise (30 min walking daily)',
            'Stress management techniques',
            'Reduce caffeine intake',
            'Follow-up if symptoms persist after 2 weeks'
        ],
        prescriptions: [
            { name: 'Alprazolam 0.25mg', dosage: 'Take as needed for anxiety, max 2 per day', duration: '2 weeks' },
            { name: 'Omeprazole 20mg', dosage: 'Once daily before breakfast', duration: '1 month' }
        ],
        nextSteps: 'Monitor symptoms and schedule ECG if chest pain persists'
    };

    const handleRatingSubmit = async () => {
        if (rating === 0) {
            alert('Please select a rating before submitting');
            return;
        }

        // In real app, send to API
        console.log('Rating submitted:', { appointmentId, rating, feedback });
        setIsSubmitted(true);
    };

    const handleDownloadSummary = async () => {
        setIsDownloading(true);

        // Simulate PDF generation
        await new Promise(resolve => setTimeout(resolve, 1500));

        // Create a simple text download for demo
        const summaryText = `
CONSULTATION SUMMARY
====================
Date: ${consultationData.date}
Doctor: ${consultationData.doctorName}
Specialty: ${consultationData.specialty}
Duration: ${consultationData.duration}

DIAGNOSIS
---------
${consultationData.diagnosis}

RECOMMENDATIONS
---------------
${consultationData.recommendations.map((r, i) => `${i + 1}. ${r}`).join('\n')}

PRESCRIPTIONS
-------------
${consultationData.prescriptions.map(p => `- ${p.name}\n  ${p.dosage} (${p.duration})`).join('\n')}

NEXT STEPS
----------
${consultationData.nextSteps}

---
Generated by HealthSync | This is a demo document
        `;

        const blob = new Blob([summaryText], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `consultation-summary-${appointmentId}.txt`;
        a.click();
        window.URL.revokeObjectURL(url);

        setIsDownloading(false);
    };

    return (
        <div className="summary-page">
            <div className="container">
                <div className="summary-content">
                    {/* Header */}
                    <div className="summary-header">
                        <div className="completion-icon">✅</div>
                        <h1>Consultation Complete</h1>
                        <p className="text-secondary">
                            Your session with {consultationData.doctorName} has ended
                        </p>
                    </div>

                    {/* Consultation Details Card */}
                    <div className="summary-card">
                        <div className="card-header">
                            <span className="header-icon">📋</span>
                            <h2>Visit Summary</h2>
                        </div>

                        <div className="detail-grid">
                            <div className="detail-item">
                                <span className="detail-label">Doctor</span>
                                <span className="detail-value">{consultationData.doctorName}</span>
                            </div>
                            <div className="detail-item">
                                <span className="detail-label">Specialty</span>
                                <span className="detail-value">{consultationData.specialty}</span>
                            </div>
                            <div className="detail-item">
                                <span className="detail-label">Date</span>
                                <span className="detail-value">{consultationData.date}</span>
                            </div>
                            <div className="detail-item">
                                <span className="detail-label">Duration</span>
                                <span className="detail-value">{consultationData.duration}</span>
                            </div>
                        </div>

                        <div className="diagnosis-section">
                            <h3>📌 Diagnosis</h3>
                            <p className="diagnosis-text">{consultationData.diagnosis}</p>
                        </div>

                        <div className="recommendations-section">
                            <h3>💡 Recommendations</h3>
                            <ul className="recommendations-list">
                                {consultationData.recommendations.map((rec, idx) => (
                                    <li key={idx}>{rec}</li>
                                ))}
                            </ul>
                        </div>

                        {consultationData.prescriptions.length > 0 && (
                            <div className="prescriptions-section">
                                <h3>💊 Prescriptions</h3>
                                <div className="prescription-cards">
                                    {consultationData.prescriptions.map((rx, idx) => (
                                        <div key={idx} className="prescription-card">
                                            <div className="rx-header">
                                                <span className="rx-icon">💊</span>
                                                <strong>{rx.name}</strong>
                                            </div>
                                            <p className="rx-dosage">{rx.dosage}</p>
                                            <span className="rx-duration">{rx.duration}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        )}

                        <div className="next-steps-section">
                            <h3>⏭️ Next Steps</h3>
                            <p>{consultationData.nextSteps}</p>
                        </div>
                    </div>

                    {/* Download Button */}
                    <button
                        className="btn btn-secondary download-btn"
                        onClick={handleDownloadSummary}
                        disabled={isDownloading}
                    >
                        {isDownloading ? (
                            <>
                                <span className="spinner-small"></span>
                                Generating...
                            </>
                        ) : (
                            <>
                                📥 Download Summary
                            </>
                        )}
                    </button>

                    {/* Rating Section */}
                    <div className="rating-card">
                        <div className="card-header">
                            <span className="header-icon">⭐</span>
                            <h2>Rate Your Experience</h2>
                        </div>

                        {!isSubmitted ? (
                            <>
                                <p className="rating-prompt">
                                    How was your consultation with {consultationData.doctorName}?
                                </p>

                                <div className="star-rating">
                                    {[1, 2, 3, 4, 5].map((star) => (
                                        <button
                                            key={star}
                                            className={`star-btn ${star <= (hoveredRating || rating) ? 'active' : ''}`}
                                            onClick={() => setRating(star)}
                                            onMouseEnter={() => setHoveredRating(star)}
                                            onMouseLeave={() => setHoveredRating(0)}
                                        >
                                            ⭐
                                        </button>
                                    ))}
                                </div>

                                <div className="rating-labels">
                                    <span>Poor</span>
                                    <span>Excellent</span>
                                </div>

                                <textarea
                                    className="feedback-input"
                                    placeholder="Share your experience (optional)..."
                                    value={feedback}
                                    onChange={(e) => setFeedback(e.target.value)}
                                    rows={3}
                                />

                                <button
                                    className="btn btn-primary submit-rating-btn"
                                    onClick={handleRatingSubmit}
                                    disabled={rating === 0}
                                >
                                    Submit Rating
                                </button>
                            </>
                        ) : (
                            <div className="rating-success">
                                <span className="success-icon">🎉</span>
                                <h3>Thank you for your feedback!</h3>
                                <p>Your rating helps us improve our services.</p>
                            </div>
                        )}
                    </div>

                    {/* Action Buttons */}
                    <div className="action-buttons">
                        <Link to="/intake" className="btn btn-primary">
                            📅 Book Another Consultation
                        </Link>
                        <Link to="/" className="btn btn-secondary">
                            🏠 Return to Home
                        </Link>
                    </div>

                    {/* Reassuring Message */}
                    <div className="reassuring-message">
                        <span className="care-emoji">💚</span>
                        <p>Thank you for choosing HealthSync. Wishing you a speedy recovery!</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ConsultationSummary;
